# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca7dba4129fba5fb2f9870419819ef937ea58942f2c83e2a0de89fd0ec10651d048afe61188c1f26d7c054af0fda7e038a8105cbfdfe9ff42e6349b5c077b658

test:
  secret_key_base: b4de131a5880c444e6975651dd4cacb46e0194020a97a57f482f9d7804cf914052ab0540d98d24dfba507b87d8b3e78ca5817f214b7145eb3614b90b318a3279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
